Repository Hi-Fi-Club/FE, pull requests merged in 2021-09, with the labels that each got.

#32 카카오 로그인 & 로그아웃 구현
  src/App.tsx
  src/components/Enter/index.tsx
  src/components/Header/index.tsx
  src/components/Routes/index.tsx
  src/pages/LoginLoadingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LogoutLoadingPage.tsx
  src/util/API.ts
  src/util/constants.ts
  src/util/funcs.ts
Labels: ✨ feature

#33 개인정보 등록 관련 페이지 url path 변경 & 관심사 등록 페이지 기능 수정
  src/components/Common/Buttons/TargetButton.tsx
  src/components/Common/Buttons/index.tsx
  src/components/Common/ResponsiveContainer/mediaQueries.ts
  src/components/Header/index.tsx
  src/components/RegisterInterest/index.tsx
  src/components/RegisterLocation/TargetButton.tsx
  src/components/Routes/index.tsx
  src/components/User/RegisterInterest/RegisterInterest.tsx
  src/components/User/RegisterInterest/index.tsx
  src/components/User/RegisterLocation/RegisterLocation.tsx
  src/components/User/RegisterLocation/index.tsx
  src/pages/InterestPage.tsx
  src/pages/LocationPage.tsx
  src/pages/User/RegisterInterestPage.tsx
  src/pages/User/RegisterLocationPage.tsx
  src/pages/index.tsx
  src/util/constants.ts
  src/util/styles/GlobalStyle.tsx
  src/util/styles/theme/styled.d.ts
Labels: 🔨 refactor, ✨ feature

#34 Bug/location 동일 동명 선택 가능
  .gitignore
  src/components/User/RegisterLocation/RegisterLocation.tsx
  yarn.lock
Labels: 🦋 fix

#38 Refactor/location
  .gitignore
  src/components/Header/index.tsx
  src/components/User/RegisterLocation/LocationClickResult.tsx
  src/components/User/RegisterLocation/LocationInput.tsx
  src/components/User/RegisterLocation/LocationSearchResult.tsx
  src/components/User/RegisterLocation/RegisterLocation.tsx
  src/components/User/RegisterLocation/index.tsx
  src/util/API.ts
  src/util/constants.ts
  yarn.lock
Labels: 🔨 refactor

#40 로그인 경로 수정
  src/components/Enter/index.tsx
  src/components/Header/index.tsx
  src/components/Routes/index.tsx
  src/components/User/RegisterInterest/RegisterInterest.tsx
  src/components/User/RegisterLocation/LocationInput.tsx
  src/components/User/RegisterLocation/index.tsx
  src/pages/EnterPage.tsx
  src/pages/LoginLoadingPage.tsx
  src/pages/auth/LoginLoadingPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/LogoutLoadingPage.tsx
  src/pages/index.tsx
  src/util/API.ts
  src/util/dataFetching/API.ts
  src/util/dataFetching/userInfo.ts
Labels: 🔨 refactor, 🦋 fix
